---
# All available hooks: https://pre-commit.com/hooks.html
# R specific hooks: https://github.com/lorenzwalthert/precommit
default_stages: [commit]
default_language_version:
  python: python3
repos:
  - repo: https://github.com/lorenzwalthert/precommit
    rev: v0.3.2.9011
    hooks:
      - id: style-files
        name: Style code with `styler`
        args:
          [--style_pkg=styler, --style_fun=tidyverse_style, --cache-root=styler]
      - id: roxygenize
        name: Regenerate package documentation
        additional_dependencies:
          - checkmate
          - digest
          - dplyr
          - ggplot2
          - glue
          - grDevices
          - lifecycle
          - logger
          - magrittr
          - methods
          - bioc::MultiAssayExperiment
          - R6
          - rlang
          - rtables
          - shinyjs
          - shinyWidgets
          - stats
          - bioc::SummarizedExperiment
          - utils
          - yaml
      - id: spell-check
        name: Check spelling with `spelling`
        exclude: >
          (?x)^(
          .*\.[rR]|
          .*\.css|
          .*\.jpg|
          .*\.js|
          .*\.png|
          .*\.py|
          .*\.RData|
          .*\.Rds|
          .*\.rds|
          .*\.Rproj|
          .*\.sh|
          .*\.svg|
          .*\.xml|
          (.*/|)\_pkgdown.y[a]ml|
          (.*/|)\.gitignore|
          (.*/|)\.gitlab-ci\.yml|
          (.*/|)\.lintr|
          (.*/|)\.pre-commit-.*|
          (.*/|)\.Rbuildignore|
          (.*/|)\.Renviron|
          (.*/|)\.Rprofile|
          (.*/|)CODEOWNERS|
          (.*/|)DESCRIPTION|
          (.*/|)LICENSE|
          (.*/|)NAMESPACE|
          (.*/|)staged_dependencies\.yaml|
          (.*/|)WORDLIST|
          \.github/.*\.yaml|
          data/.*
          )$
      - id: lintr
        exclude: >
          (?x)^(
          design/.*
          )$
        additional_dependencies:
          - checkmate
          - digest
          - dplyr
          - ggplot2
          - glue
          - grDevices
          - lifecycle
          - logger
          - magrittr
          - methods
          - bioc::MultiAssayExperiment
          - R6
          - rlang
          - rtables
          - shinyjs
          - shinyWidgets
          - stats
          - bioc::SummarizedExperiment
          - utils
          - yaml
      - id: readme-rmd-rendered
      - id: parsable-R
        exclude: >
          (?x)^(
          design/.*
          )$
      - id: no-browser-statement
      - id: deps-in-desc
        exclude: >
          (?x)^(
          design/.*
          )$
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.9-for-vscode
    hooks:
      - id: prettier
        exclude: >
          (?x)^(
          design/.*
          )$
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=1000"]
      - id: end-of-file-fixer
        exclude: >
          (?x)^(
          .*\.Rd|
          tests/testthat/_snaps/.*
          )$
      - id: trailing-whitespace
        exclude: >
          (?x)^(
          .*\.Rd|
          tests/testthat/_snaps/.*
          )$
      - id: check-yaml
      - id: no-commit-to-branch
      - id: mixed-line-ending
        args: ["--fix=lf"]
  - repo: local
    hooks:
      - id: forbid-to-commit
        name: Don't commit common R artifacts
        entry: Cannot commit .Rhistory, .RData, .Rds or .rds.
        language: fail
        files: '\.Rhistory|\.RData|\.Rds|\.rds$'
        # `exclude: <regex>` to allow committing specific files
