---
title: "PCA module design" 
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source("https://raw.github.roche.com/gist/sabanesd/0e839ca7d4920fab342d8ed4b9d668fc/raw/eeaf752448e1b07641cc0c2a3af2172af7b99c94/install_nest.R")
install_nest("teal", "cb200aa2738f820b9dcffaffd858581fad9cf90e")
library(teal)
library(teal.devel)
library(dplyr)
library(ggplot2)
library(random.cdisc.data)
library(hermes)
library(assertthat)
```

## Hermes functions we want to use for this module

```{r}
object <- HermesData(summarized_experiment) %>%
  add_quality_flags() %>% 
  filter() %>% 
  normalize()


result <- calc_pca(object)
result <- calc_pca(object, assay_name = "tpm")

result_cpm <- calc_pca(object, assay_name = "cpm")
autoplot(result)
autoplot(result, x = 2, y = 3)
autoplot(result, variance_percentage = FALSE)
autoplot(result, label = TRUE, label.repel = TRUE)
autoplot(result, label = TRUE, label.repel = FALSE)
```

## Teal module

``` {r}
tm_g_pca <- function(label,
                     mae_name,
                     pre_output = NULL,
                     post_output = NULL) {
  assert_string(label)
  assert_string(mae_name)
  assert_tag(pre_output, null.ok = TRUE)
  assert_tag(post_output, null.ok = TRUE)

  module(
    label = label,
    server = srv_g_pca,
    server_args = list(
      mae_name = mae_name
    ),
    ui = ui_g_pca,
    ui_args = list(
      mae_name = mae_name,
      pre_output = pre_output,
      post_output = post_output
    ),
    filters = "all"
  )
}
```

## UI function
User-defined inputs for PCA plot:
1. object
2. assay_name
3. variance_percentage
4. label & label.repel

Do we filter on QC flags and normalize? Or let user provide inputs for any of these?

``` {r}
ui_g_pca <- function(id,
                     datasets,
                     mae_name,
                     pre_output,
                     post_output) {
  ns <- NS(id)
  mae <- datasets$get_data(mae_name, filtered = FALSE)
  experiment_name_choices <- names(mae)

  teal.devel::standard_layout(
    encoding = div(
      tags$label("Encodings", class = "text-primary"),
      helpText("Analysis of MAE:", tags$code(mae_name)),
      selectInput(ns("experiment_name"), "Select experiment", experiment_name_choices),
      selectInput(ns("assay_name"), "Select assay", choices = ""),
      selectizeInput(ns("x_var"), "Select Principal Component to Plot on X-axis", choices = ""),
      selectizeInput(ns("y_var"), "Select Principal Component to Plot on Y-axis", choices = ""),
      tags$label("Show Variance Percentage"),
      shinyWidgets::switchInput(ns("var_pct"), value = TRUE, size = "mini"),
      tags$label("Show Sample Label"),
      shinyWidgets::switchInput(ns("label"), value = TRUE, size = "mini"),
    ),
    output = plotOutput(ns("plot")),
    pre_output = pre_output,
    post_output = post_output
  )
}
```


``` {r}
srv_g_pca <- function(input,
                      output,
                      session,
                      datasets,
                      mae_name) {}

```


## Sample app

``` {r}
sample_tm_g_pca <- function() {
  mae <- hermes::multi_assay_experiment
  for (i in seq_along(mae)) {
    mae[[i]] <- hermes::HermesData(mae[[i]])
  }
  mae_data <- dataset("MAE", mae)
  data <- teal_data(mae_data)
  app <- init(
    data = data,
    modules = root_modules(
      static = {
        tm_g_pca(
          label = "pca plot",
          mae_name = "MAE"
        )
      }
    )
  )
  shinyApp(app$ui, app$server)
}

```

``` {r}
sample_tm_g_pca()
```

