---
title: "Survival forest plot module design" 
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(dplyr)
library(tern)
library(teal)
library(teal.devel)
library(teal.modules.hermes)
library(hermes)
library(assertthat)
library(checkmate)
```

## Survival forest plot module design

We want to design a simple survival forest plot teal module.

## General module workflow

```{r}
# Example ADSL data converted into a CDISCDataset object.
adsl <- cdisc_dataset("ADSL", ex_adsl)

# Example ADTTE data converted into a CDISCDataset object.
adtte <- cdisc_dataset("ADTTE", ex_adtte)

# Example MAE data and merge datasets.
MAE <- multi_assay_experiment
mae <- dataset("MAE", MAE)
data <- teal_data(mae, adsl, adtte) %>%
  mutate_join_keys("MAE", "MAE", c("STUDYID", "USUBJID"))

# Get raw ADTTE.
adtte_raw <- get_raw_data(adtte)

# Merge ADTTE with counts of specified gene from MAE.
# Copied helper function (h_km_mae_to_adtte) from Lyndsee's (30_km_mod) feature branch for now for this to work
adtte_final <- h_km_mae_to_adtte(
  adtte_raw,
  MAE,
  gene_var = "GeneID:1820",
  experiment_name = "hd2"
)

# Create new gene bin variable in the ADTTE.
colname <- attr(adtte_final, "gene_cols")
probs <- 0.5

adtte_final <- adtte_final %>%
  df_explicit_na() %>%
  mutate(
    AVAL = day2month(AVAL),
    AVALU = "Months",
    is_event = CNSR == 0,
    gene_bin = tern::cut_quantile_bins(
      adtte_final[[colname]],
      probs = probs,
      labels = c("Low", "High")
    )
  )

# Calculate survival forest results.
tbl <- extract_survival_subgroups(
  variables = list(
    tte = "AVAL",
    is_event = "is_event",
    arm = "gene_bin",
    subgroups = c("BEP01FL", "BMRKR2")
  ),
  label_all = "All Patients",
  data = adtte_final
)

# Tabulate results.
result <- basic_table() %>%
  tabulate_survival_subgroups(
    df = tbl,
    vars = c("n_tot_events", "n", "n_events", "median", "hr", "ci"),
    time_unit = adtte_final$AVALU[1]
  )

# Plot result.
g_forest(result)
```


## Plot function


```{r}
draw_surv_forest <- function(adtte_data, mae, experiment_name, assay_name, geneid, probs, subgroups) {
  assert_that(
    is.string(experiment_name),
    is.string(assay_name)
  )

  adtte <- h_km_mae_to_adtte(
    adtte_data,
    mae,
    gene_var = geneid,
    experiment_name = experiment_name,
    assay_name = assay_name
  )
  colname <- attr(adtte, "gene_cols")

  adtte_final <- adtte %>%
    df_explicit_na() %>%
    mutate(
      AVAL = day2month(AVAL),
      AVALU = "Months",
      is_event = CNSR == 0,
      gene_bin = cut_quantile_bins(
        adtte[[colname]],
        probs = probs,
        labels = c("Low", "High")
      )
    )

  tbl <- extract_survival_subgroups(
    variables = list(
      tte = "AVAL",
      is_event = "is_event",
      arm = "gene_bin",
      subgroups = subgroups
    ),
    label_all = "All Patients",
    data = adtte_final
  )

  result <- basic_table() %>%
    tabulate_survival_subgroups(
      df = tbl,
      vars = c("n_tot_events", "n", "n_events", "median", "hr", "ci"),
      time_unit = adtte_final$AVALU[1]
    )

  g_forest(result)
}
```

Test it:

```{r}
adtte_test <- rtables::ex_adtte
MAE <- multi_assay_experiment

draw_surv_forest(
  adtte_test,
  MAE,
  experiment_name = "hd2",
  assay_name = "counts",
  geneid = "GeneID:1820",
  probs = 0.8,
  subgroups = c("BEP01FL", "BMRKR2")
)
```

## UI function


```{r}
ui_surv_forest <- function(id, datasets, dataname) {
  ns <- NS(id)
  mae <- datasets$get_data(dataname, filtered = TRUE)
  experiment_name_choices <- names(mae)
  teal.devel::standard_layout(
    encoding = div(
      tags$label("Encodings", class = "text-primary"),
      helpText("Analysis of MAE:", tags$code(dataname)),
      selectInput(ns("experiment_name"), "Select Experiment", experiment_name_choices),
      selectInput(ns("assay_name"), "Select Assay", choices = ""),
      selectizeInput(ns("geneid"), "Gene ID", choices = ""),
      sliderInput(ns("probs"), label = ("Probability Cutoff"), min = 0.01, max = 0.99, value = 0.5),
      optionalSelectInput(ns("subgroups"), label = "Subgroups", choices = "", selected = "", multiple = TRUE)
    ),
    output = plotOutput(ns("plot"))
  )
}
```

## Server function

```{r}
srv_surv_forest <- function(input, output, session, datasets, dataname) {
  
  # When the filtered data set of the chosen experiment changes, update the
  # experiment data object.
  experiment_data <- reactive({
    experiment_name <- input$experiment_name
    req(input$experiment_name) # Important to avoid running into NULL here.

    mae <- datasets$get_data(dataname, filtered = TRUE)
    mae[[input$experiment_name]]
  })

  # When the chosen experiment changes, recompute the available assay.
  assay_names <- eventReactive(input$experiment_name, ignoreNULL = FALSE, {
    object <- experiment_data()
    SummarizedExperiment::assayNames(object)
  })

  # When the chosen experiment changes, recompute the available genes.
  genes <- eventReactive(input$experiment_name, ignoreNULL = FALSE, {
    object <- experiment_data()
    rownames(object)
  })

  # When the chosen experiment changes, recompute the available colData.
  subgroups <- eventReactive(input$experiment_name, {
    adtte <- datasets$get_data("ADTTE", filtered = TRUE)
    colnames(adtte)
  })

  # When the assay names change, update the choices for assay.
  observeEvent(assay_names(), {
    assay_name_choices <- assay_names()

    updateSelectInput(
      session,
      "assay_name",
      choices = assay_name_choices,
      selected = assay_name_choices[1]
    )
  })

  # When the genes are recomputed, update the choice for genes in the UI.
  observeEvent(genes(), {
    gene_choices <- genes()

    updateSelectizeInput(
      session,
      "geneid",
      choices = gene_choices,
      selected = gene_choices[1],
      server = TRUE
    )
  })

  observeEvent(subgroups(), {
    subgroup_choices <- subgroups()

    updateOptionalSelectInput(
      session,
      "subgroups",
      choices = subgroup_choices,
      selected = subgroup_choices[1]
    )
  })

  adtte_counts <- reactive({
    mae <- datasets$get_data(dataname, filtered = TRUE)
    adtte <- datasets$get_data("ADTTE", filtered = TRUE)
    geneid <- input$geneid
    experiment_name <- input$experiment_name
    assay_name <- input$assay_name

    req(geneid, experiment_name, assay_name)

    h_km_mae_to_adtte(
      adtte,
      mae,
      gene_var = geneid,
      experiment_name = experiment_name,
      assay_name = assay_name
    )
  })

  adtte_final <- reactive({
    adtte_counts <- adtte_counts()
    probs <- input$probs
    colname <- attr(adtte_counts, "gene_cols")

    adtte_counts %>%
      df_explicit_na() %>%
      mutate(
        AVAL = day2month(AVAL),
        AVALU = "Months",
        is_event = CNSR == 0,
        gene_bin = tern::cut_quantile_bins(
          adtte_counts[[colname]],
          probs = probs,
          labels = c("Low", "High")
        )
      )
  })

  tbl <- reactive({
    adtte_final <- adtte_final()
    subgroups <- input$subgroups

    tern::extract_survival_subgroups(
      variables = list(
        tte = "AVAL",
        is_event = "is_event",
        arm = "gene_bin",
        subgroups = subgroups
      ),
      label_all = "All Patients",
      data = adtte_final
    )
  })

  result <- reactive({
    tbl <- tbl()

    rtables::basic_table() %>%
      tern::tabulate_survival_subgroups(
        df = tbl,
        vars = c("n_tot_events", "n", "n_events", "median", "hr", "ci"),
        time_unit = adtte_final()$AVALU[1]
      )
  })

  output$plot <- renderPlot({
    result <- result()
    tern::g_forest(result)
  })
}
```

## Teal module function

```{r}
tm_g_surv_forest <- function(label = "Simple MAE module",
                             info = NULL,
                             dataname = NULL,
                             pre_output = NULL,
                             post_output = NULL) {
  module(
    label = label,
    server = srv_surv_forest,
    ui = ui_surv_forest,
    ui_args = list(dataname = dataname),
    server_args = list(dataname = dataname),
    filters = "all"
  )
}
```

## Try it out

Now we can try it out.

```{r}
app <- init(
  data = data,
  modules = root_modules(
    static = {
      tm_g_surv_forest(
        label = "forest",
        dataname = "MAE"
      )
    }
  )
)

shinyApp(app$ui, app$server)
```
