app <- ShinyDriver$new("../../")
app$snapshotInit("mytest")

app$setInputs(`teal-main_ui-modules_ui-root_pca-var_pct` = TRUE)
app$setInputs(`teal-main_ui-modules_ui-root_pca-label` = TRUE)
app$setInputs(`teal-main_ui-modules_ui-root_pca-cluster_columns` = FALSE)
app$setInputs(`teal-main_ui-modules_ui-root_pca-show_matrix` = TRUE)
app$setInputs(`teal-main_ui-modules_ui-root_pca-color_var` = character(0))
app$setInputs(`teal-main_ui-filter_panel-add_MAE_filter-subjects-var_to_add` = character(0))
app$setInputs(`teal-main_ui-filter_panel-add_MAE_filter-hd1-row_to_add` = character(0))
app$setInputs(`teal-main_ui-filter_panel-add_MAE_filter-hd1-col_to_add` = character(0))
app$setInputs(`teal-main_ui-filter_panel-add_MAE_filter-hd2-row_to_add` = character(0))
app$setInputs(`teal-main_ui-filter_panel-add_MAE_filter-hd2-col_to_add` = character(0))
app$setInputs(`teal-main_ui-filter_panel-add_MAE_filter-hd3-row_to_add` = character(0))
app$setInputs(`teal-main_ui-filter_panel-add_MAE_filter-hd3-col_to_add` = character(0))
app$setInputs(`teal-main_ui-modules_ui-root` = "pca")
app$setInputs(`teal-main_ui-modules_ui-root_pca-tab_selected` = "PCA")
app$setInputs(`teal-main_ui-filter_panel-remove_all_filters` = "click")
app$setInputs(`teal-main_ui-filter_panel-MAE_filters-remove_filters` = "click")
app$setInputs(`teal-main_ui-modules_ui-root_pca-experiment_name` = "hd1")
app$setInputs(`teal-main_ui-modules_ui-root_pca-assay_name` = "")
app$setInputs(`teal-main_ui-modules_ui-root_pca-x_var` = "")
app$setInputs(`teal-main_ui-modules_ui-root_pca-y_var` = "")
app$snapshot()
app$setInputs(`teal-main_ui-filter_panel-add_MAE_filter-subjects-var_to_add` = "sex")
app$snapshot()
app$setInputs(`teal-main_ui-filter_panel-add_MAE_filter-subjects-73212989ea55791d16811d753ac43de0-content-selection` = "M")
app$snapshot()
app$setInputs(`teal-main_ui-filter_panel-add_MAE_filter-subjects-73212989ea55791d16811d753ac43de0-content-selection` = c("F", "M"))
app$snapshot()
app$setInputs(`teal-main_ui-filter_panel-add_MAE_filter-subjects-73212989ea55791d16811d753ac43de0-content-selection` = "F")
app$snapshot()
