app <- ShinyDriver$new("../../")
app$snapshotInit("mytest")

app$setInputs(`teal-main_ui-modules_ui-root_sampleVarSpec_example-facet_var-sample_var` = character(0))
app$setInputs(`teal-main_ui-filter_panel-add_MAE_filter-subjects-var_to_add` = character(0))
app$setInputs(`teal-main_ui-filter_panel-add_MAE_filter-hd1-row_to_add` = character(0))
app$setInputs(`teal-main_ui-filter_panel-add_MAE_filter-hd1-col_to_add` = character(0))
app$setInputs(`teal-main_ui-filter_panel-add_MAE_filter-hd2-row_to_add` = character(0))
app$setInputs(`teal-main_ui-filter_panel-add_MAE_filter-hd2-col_to_add` = character(0))
app$setInputs(`teal-main_ui-filter_panel-add_MAE_filter-hd3-row_to_add` = character(0))
app$setInputs(`teal-main_ui-filter_panel-add_MAE_filter-hd3-col_to_add` = character(0))
app$setInputs(`teal-main_ui-modules_ui-root` = "sampleVarSpec example")
app$setInputs(`teal-main_ui-modules_ui-root_sampleVarSpec_example-facet_var-levels_button` = "click")
app$setInputs(`teal-main_ui-filter_panel-remove_all_filters` = "click")
app$setInputs(`teal-main_ui-filter_panel-MAE_filters-remove_filters` = "click")
app$setInputs(`teal-main_ui-modules_ui-root_sampleVarSpec_example-experiment_name` = "hd1")
app$setInputs(`teal-main_ui-modules_ui-root_sampleVarSpec_example-facet_var-sample_var` = "AGE18")
app$setInputs(`teal-main_ui-modules_ui-root_sampleVarSpec_example-facet_var-levels_button` = "click")
app$setInputs(`teal-main_ui-modules_ui-root_sampleVarSpec_example-facet_var-comb_assignment` = c("1", "2"))
app$setInputs(`teal-main_ui-modules_ui-root_sampleVarSpec_example-facet_var-ok` = "click")
app$setInputs(`teal-main_ui-modules_ui-root_sampleVarSpec_example-facet_var-comb_assignment` = c("1", "1"))
app$setInputs(`teal-main_ui-modules_ui-root_sampleVarSpec_example-facet_var-ok` = "click")
app$snapshot()
