app <- ShinyDriver$new("../../")
app$snapshotInit("mytest")

app$setInputs(`teal-main_ui-modules_ui-root_boxplot-jitter` = FALSE)
app$setInputs(`teal-main_ui-modules_ui-root_boxplot-color_var` = character(0))
app$setInputs(`teal-main_ui-modules_ui-root_boxplot-facet_var` = character(0))
app$setInputs(`teal-main_ui-filter_panel-add_MAE_filter-subjects-var_to_add` = character(0))
app$setInputs(`teal-main_ui-filter_panel-add_MAE_filter-hd1-row_to_add` = character(0))
app$setInputs(`teal-main_ui-filter_panel-add_MAE_filter-hd1-col_to_add` = character(0))
app$setInputs(`teal-main_ui-filter_panel-add_MAE_filter-hd2-row_to_add` = character(0))
app$setInputs(`teal-main_ui-filter_panel-add_MAE_filter-hd2-col_to_add` = character(0))
app$setInputs(`teal-main_ui-filter_panel-add_MAE_filter-hd3-row_to_add` = character(0))
app$setInputs(`teal-main_ui-filter_panel-add_MAE_filter-hd3-col_to_add` = character(0))
app$setInputs(`teal-main_ui-modules_ui-root` = "boxplot")
app$setInputs(`teal-main_ui-filter_panel-remove_all_filters` = "click")
app$setInputs(`teal-main_ui-filter_panel-MAE_filters-remove_filters` = "click")
app$setInputs(`teal-main_ui-modules_ui-root_boxplot-experiment_name` = "hd1")
app$setInputs(`teal-main_ui-modules_ui-root_boxplot-assay_name` = "")
app$setInputs(`teal-main_ui-modules_ui-root_boxplot-genes` = character(0))
app$setInputs(`teal-main_ui-modules_ui-root_boxplot-x_var` = "")
app$setInputs(`teal-main_ui-modules_ui-root_boxplot-genes` = "GeneID:101927746")
app$snapshot()
app$setInputs(`teal-main_ui-modules_ui-root_boxplot-experiment_name` = "hd3")
app$setInputs(`teal-main_ui-modules_ui-root_boxplot-x_var` = "Filename")
app$setInputs(`teal-main_ui-modules_ui-root_boxplot-genes` = "GeneID:5205")
app$snapshot()
app$setInputs(`teal-main_ui-modules_ui-root_boxplot-jitter` = TRUE)
app$snapshot()
